### ISSUE TITLE
Error: GraphQL Client: Not Found

### ISSUE THREAD

**Issue by Zellokr** [konkonam/nuxt-shopify#15]
Hi, I've been trying the module, but I got this error when I'm trying to fetch data from my shopify store. I followed the steps from the docs. but maybe I forgot something.

error: {
    "networkStatusCode": 404,
    "message": "GraphQL Client: Not Found",
    "response": {}
}

Thank you for advance! :)

**Comment by freb97** [comment]
Hey @Zellokr,

Thanks for trying out the module!

I may have an idea what could have gone wrong. Have you set the module variables via:

```ts
shopify: {
    name: process.env...
    ...
}
```

or with the runtimeConfig?

```ts
runtimeConfig: {
    shopify: {
        name: process.env...
        ...
    }
}
```

Right now, we don't support loading from the runtimeConfig via the `NUXT_` prefixed variables. I'll look into implementing this ASAP.

Otherwise, if the env handling doesn't resolve your problem, could you maybe give us a bit more detail or a reproduction of the problem?

Thanks!

**Comment by Zellokr** [comment]
Thank you for the quick response!

Actually I'm not using runtimeConfig. My nuxt config is:

`export default defineNuxtConfig({
  compatibilityDate: "2024-11-01",
  devtools: { enabled: true },
  modules: [
    "@nuxtjs/tailwindcss",
    "nuxt-mdi",
    "nuxt-svgo",
    "shadcn-nuxt",
    "@nuxtjs/color-mode",
    "@konkonam/nuxt-shopify",
  ],
  shopify: {
    name: "tutiendaglobal",
    clients: {
      storefront: {
        apiVersion: "2024-10",
        publicAccessToken: process.env.SHOPIFY_TOKEN_STOREFRONT,
      },
    },
  },
});`

my api file is products.ts `
export default defineEventHandler(async () => {
  const storefront = useStorefront();

  return await storefront.request(
    `#graphql
        query FetchProducts($first: Int) {
            products(first: $first) {
                nodes {
                    id
                    title
                    description
                }
            }
        }
    `,
    {
      variables: {
        first: 3,
      },
    },
  );
});
`

and my index.vue 

`const { data, error } = await useFetch("/api/products");
console.log(data.value);
`

![image](https://github.com/user-attachments/assets/a05c2d1f-d762-484e-a152-cd01f81b4f51)

**Comment by freb97** [comment]
Hm, i couldn't find your store with https://tutiendaglobal.myshopify.com/, are you sure you're using the right name?

Also, we don't use the GraphQL client package, we already provide a typed client. Your file `/api/product.ts` could look like this:

```ts
export default defineEventHandler(async () => {
    const storefront = useStorefront()

    return await storefront.request(`#graphql
        query FetchProducts($first: Int) {
            products(first: $first) {
                nodes {
                    id
                    title
                    description
                }
            }
        }
    `, {
        variables: {
            first: 1,
        },
    })
})
```

**Comment by freb97** [comment]
The useStorefront import also comes from our module, it's available via your nitro imports:

```ts
import { useStorefront } from '#imports'
```

**Comment by Zellokr** [comment]
Okay, I'm using free trial version of shopify, I guess this is the name that they assign: ng7gm0-br.myshopify.com

I add a product just for testing

![image](https://github.com/user-attachments/assets/9cf82b93-d071-4b53-86bb-8f6eaeb8b710)

I'm sorry, I'm new in shopify

**Comment by freb97** [comment]
@Zellokr no worries! Did changing the name fix the issue or does the fetch still not work?

Otherwise let me know if i can help :)

**Comment by Zellokr** [comment]
Now the fetch failed:

`errors: {message: 'GraphQL Client: fetch failed'}`

**Comment by freb97** [comment]
Can you share the contents of your `/server/api/products.ts` file?

**Comment by Zellokr** [comment]
`export default defineEventHandler(async () => {
  const storefront = useStorefront();

  return await storefront.request(
    `#graphql
        query FetchProducts($first: Int) {
            products(first: $first) {
                nodes {
                    id
                    title
                    description
                }
            }
        }
    `,
    {
      variables: {
        first: 1,
      },
    },
  );
});
`

**Comment by freb97** [comment]
Just to make sure that your token gets read correctly, you could try adding it directly in the nuxt.config.ts and see if that resolves your issue. I couldn't see the error from your screenshots, everything looks correct to me.

**Comment by Zellokr** [comment]
Wow, actually worked, something is wrong with env variables.

Thank you so much for the answer!

**Comment by freb97** [comment]
Ah, nice! I'm glad that it works for you now.

Have fun with the module y buenas noches :)
